[package]
name = "ray-tracing-webgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.0"
env_logger = "0.11.3"
image = "0.25.1"
log = "0.4.21"
pollster = "0.3.0"
wgpu = "0.20.0"
winit = "0.30.0"

[features]
default = []
debug-texture = []
